// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaU7eqP0znTr_a5_vhN4MY5jF_w031xyw',
    appId: '1:893982313010:web:af765a73a0d848a9358a2b',
    messagingSenderId: '893982313010',
    projectId: 'flutter-chat-app-929bb',
    authDomain: 'flutter-chat-app-929bb.firebaseapp.com',
    storageBucket: 'flutter-chat-app-929bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHyK8MQaOUQZk11D7IseM-TxerdxgPaSk',
    appId: '1:893982313010:android:781e05b9b9795111358a2b',
    messagingSenderId: '893982313010',
    projectId: 'flutter-chat-app-929bb',
    storageBucket: 'flutter-chat-app-929bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQC8G9ffh_typW17DM-46gtFDMyo5CKq8',
    appId: '1:893982313010:ios:947aa983d5e408f7358a2b',
    messagingSenderId: '893982313010',
    projectId: 'flutter-chat-app-929bb',
    storageBucket: 'flutter-chat-app-929bb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQC8G9ffh_typW17DM-46gtFDMyo5CKq8',
    appId: '1:893982313010:ios:947aa983d5e408f7358a2b',
    messagingSenderId: '893982313010',
    projectId: 'flutter-chat-app-929bb',
    storageBucket: 'flutter-chat-app-929bb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaU7eqP0znTr_a5_vhN4MY5jF_w031xyw',
    appId: '1:893982313010:web:75334bce997d0d2c358a2b',
    messagingSenderId: '893982313010',
    projectId: 'flutter-chat-app-929bb',
    authDomain: 'flutter-chat-app-929bb.firebaseapp.com',
    storageBucket: 'flutter-chat-app-929bb.appspot.com',
  );
}
